import Head from 'next/head';
import Countdown from 'react-countdown';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Arewa Books</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h3
					style={{
						fontSize: 28,
						fontWeight: 100,
						textTransform: 'uppercase',
						letterSpacing: 5,
						margin: 16,
						color: 'rgba(0,0,0,.2)',
					}}>
					Coming Soon in
				</h3>
				<Countdown date={new Date(1636906548 * 1000)} renderer={renderer} />
			</main>

			<footer className={styles.footer}>
				<p>Powered by thinkcrypt.io</p>
			</footer>
		</div>
	);
}

const DateText = ({ value, children }) => {
	return (
		<div className={styles.numberContainer}>
			<span className={styles.value}>{value < 10 ? `0${value}` : value}</span>
			<span className={styles.text}>{children}</span>
		</div>
	);
};

const renderer = ({ days, hours, minutes, seconds, completed }) => {
	if (completed) {
		// Render a completed state
		return <div>Completed</div>;
	} else {
		// Render a countdown
		return (
			<div className={styles.whole}>
				<DateText value={days}>days</DateText>
				<DateText value={hours}>hours</DateText>
				<DateText value={minutes}>minutes</DateText>
				<DateText value={seconds}>seconds</DateText>
			</div>
		);
	}
};
